spring:
  application:
    name: Okos Orarend

  profiles:
    active: h2

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: orarendalkalmazasszakdolgozat@gmail.com
    password: ekly xcrj kdzo kqab
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.mail: DEBUG

gemini:
  enabled: true
  model: gemini-2.5-flash
  temperature: 0.3
  maxOutputTokens: 512
  chunkSize: 8000
  chunkOverlap: 400
  enableGoogleSearch: false

app:
  upload-dir: uploads
